title: "My Blog"
description: "A platform where I write about my experiences, insights, and learnings on web development, design, and tech."
baseurl: "/blogs"
url: "https://ruchiikr.github.io"
theme: minima

# Custom permalink structure to remove date from URLs
permalink: "/:title/"
