title: "My Blog"
description: "Insights and tips on becoming a skilled Full-Stack Developer."
baseurl: "/blogs"
url: "https://ruchiikr.github.io"
theme: minima

# Custom permalink structure to remove date from URLs
permalink: "/:title/"
