site_name: "Tech Hiring Guide"
site_description: "Your go-to resource for hiring top tech talent, including fullstack developers."
site_url: "https://ruchiikr.github.io"
theme: material
nav:
  - Home: index.md
  - Hiring Fullstack Developer: hiring-fullstack-developer.md
  - About: about.md
  - Contact: contact.md
plugins:
  - search
  - markdown-extradata
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.extra
  - pymdownx.superfences
