title: "My Blog"
description: "Guides and insights on hiring the best Full-Stack Developers."
baseurl: "/blogs"
url: "https://ruchiikr.github.io"
theme: minima

# Custom permalink structure to remove date from URLs
permalink: "/:title/"
